// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: bank.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on CreateAccountReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateAccountReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAccountReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAccountReqMultiError, or nil if none found.
func (m *CreateAccountReq) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAccountReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetOwner()) < 1 {
		err := CreateAccountReqValidationError{
			field:  "Owner",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Currency

	if len(errors) > 0 {
		return CreateAccountReqMultiError(errors)
	}

	return nil
}

// CreateAccountReqMultiError is an error wrapping multiple validation errors
// returned by CreateAccountReq.ValidateAll() if the designated constraints
// aren't met.
type CreateAccountReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAccountReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAccountReqMultiError) AllErrors() []error { return m }

// CreateAccountReqValidationError is the validation error returned by
// CreateAccountReq.Validate if the designated constraints aren't met.
type CreateAccountReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAccountReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAccountReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAccountReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAccountReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAccountReqValidationError) ErrorName() string { return "CreateAccountReqValidationError" }

// Error satisfies the builtin error interface
func (e CreateAccountReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAccountReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAccountReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAccountReqValidationError{}

// Validate checks the field values on CreateAccountRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *CreateAccountRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateAccountRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateAccountRspMultiError, or nil if none found.
func (m *CreateAccountRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateAccountRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetCreatedAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateAccountRspValidationError{
					field:  "CreatedAccount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateAccountRspValidationError{
					field:  "CreatedAccount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateAccountRspValidationError{
				field:  "CreatedAccount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateAccountRspMultiError(errors)
	}

	return nil
}

// CreateAccountRspMultiError is an error wrapping multiple validation errors
// returned by CreateAccountRsp.ValidateAll() if the designated constraints
// aren't met.
type CreateAccountRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateAccountRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateAccountRspMultiError) AllErrors() []error { return m }

// CreateAccountRspValidationError is the validation error returned by
// CreateAccountRsp.Validate if the designated constraints aren't met.
type CreateAccountRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateAccountRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateAccountRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateAccountRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateAccountRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateAccountRspValidationError) ErrorName() string { return "CreateAccountRspValidationError" }

// Error satisfies the builtin error interface
func (e CreateAccountRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateAccountRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateAccountRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateAccountRspValidationError{}

// Validate checks the field values on Account with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Account) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Account with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AccountMultiError, or nil if none found.
func (m *Account) ValidateAll() error {
	return m.validate(true)
}

func (m *Account) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Owner

	// no validation rules for Balance

	// no validation rules for Currency

	if all {
		switch v := interface{}(m.GetCreateAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AccountValidationError{
					field:  "CreateAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AccountValidationError{
					field:  "CreateAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreateAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AccountValidationError{
				field:  "CreateAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AccountMultiError(errors)
	}

	return nil
}

// AccountMultiError is an error wrapping multiple validation errors returned
// by Account.ValidateAll() if the designated constraints aren't met.
type AccountMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AccountMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AccountMultiError) AllErrors() []error { return m }

// AccountValidationError is the validation error returned by Account.Validate
// if the designated constraints aren't met.
type AccountValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AccountValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AccountValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AccountValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AccountValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AccountValidationError) ErrorName() string { return "AccountValidationError" }

// Error satisfies the builtin error interface
func (e AccountValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAccount.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AccountValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AccountValidationError{}

// Validate checks the field values on GetAccountReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAccountReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAccountReqMultiError, or
// nil if none found.
func (m *GetAccountReq) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetId() <= 0 {
		err := GetAccountReqValidationError{
			field:  "Id",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return GetAccountReqMultiError(errors)
	}

	return nil
}

// GetAccountReqMultiError is an error wrapping multiple validation errors
// returned by GetAccountReq.ValidateAll() if the designated constraints
// aren't met.
type GetAccountReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountReqMultiError) AllErrors() []error { return m }

// GetAccountReqValidationError is the validation error returned by
// GetAccountReq.Validate if the designated constraints aren't met.
type GetAccountReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountReqValidationError) ErrorName() string { return "GetAccountReqValidationError" }

// Error satisfies the builtin error interface
func (e GetAccountReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountReqValidationError{}

// Validate checks the field values on GetAccountRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *GetAccountRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAccountRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in GetAccountRspMultiError, or
// nil if none found.
func (m *GetAccountRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAccountRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAccountRspValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAccountRspValidationError{
					field:  "Account",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAccountRspValidationError{
				field:  "Account",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAccountRspMultiError(errors)
	}

	return nil
}

// GetAccountRspMultiError is an error wrapping multiple validation errors
// returned by GetAccountRsp.ValidateAll() if the designated constraints
// aren't met.
type GetAccountRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAccountRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAccountRspMultiError) AllErrors() []error { return m }

// GetAccountRspValidationError is the validation error returned by
// GetAccountRsp.Validate if the designated constraints aren't met.
type GetAccountRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAccountRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAccountRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAccountRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAccountRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAccountRspValidationError) ErrorName() string { return "GetAccountRspValidationError" }

// Error satisfies the builtin error interface
func (e GetAccountRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAccountRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAccountRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAccountRspValidationError{}

// Validate checks the field values on ListAccountsReq with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListAccountsReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAccountsReq with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAccountsReqMultiError, or nil if none found.
func (m *ListAccountsReq) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAccountsReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if val := m.GetLimit(); val < 5 || val > 10 {
		err := ListAccountsReqValidationError{
			field:  "Limit",
			reason: "value must be inside range [5, 10]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Offset

	if len(errors) > 0 {
		return ListAccountsReqMultiError(errors)
	}

	return nil
}

// ListAccountsReqMultiError is an error wrapping multiple validation errors
// returned by ListAccountsReq.ValidateAll() if the designated constraints
// aren't met.
type ListAccountsReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAccountsReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAccountsReqMultiError) AllErrors() []error { return m }

// ListAccountsReqValidationError is the validation error returned by
// ListAccountsReq.Validate if the designated constraints aren't met.
type ListAccountsReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAccountsReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAccountsReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAccountsReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAccountsReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAccountsReqValidationError) ErrorName() string { return "ListAccountsReqValidationError" }

// Error satisfies the builtin error interface
func (e ListAccountsReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAccountsReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAccountsReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAccountsReqValidationError{}

// Validate checks the field values on ListAccountsRsp with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListAccountsRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAccountsRsp with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAccountsRspMultiError, or nil if none found.
func (m *ListAccountsRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAccountsRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAccounts() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAccountsRspValidationError{
						field:  fmt.Sprintf("Accounts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAccountsRspValidationError{
						field:  fmt.Sprintf("Accounts[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAccountsRspValidationError{
					field:  fmt.Sprintf("Accounts[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ListAccountsRspMultiError(errors)
	}

	return nil
}

// ListAccountsRspMultiError is an error wrapping multiple validation errors
// returned by ListAccountsRsp.ValidateAll() if the designated constraints
// aren't met.
type ListAccountsRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAccountsRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAccountsRspMultiError) AllErrors() []error { return m }

// ListAccountsRspValidationError is the validation error returned by
// ListAccountsRsp.Validate if the designated constraints aren't met.
type ListAccountsRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAccountsRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAccountsRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAccountsRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAccountsRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAccountsRspValidationError) ErrorName() string { return "ListAccountsRspValidationError" }

// Error satisfies the builtin error interface
func (e ListAccountsRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAccountsRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAccountsRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAccountsRspValidationError{}

// Validate checks the field values on TransferReq with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TransferReq) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferReq with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TransferReqMultiError, or
// nil if none found.
func (m *TransferReq) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferReq) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if m.GetFromAccountId() <= 0 {
		err := TransferReqValidationError{
			field:  "FromAccountId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetToAccountId() <= 0 {
		err := TransferReqValidationError{
			field:  "ToAccountId",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if m.GetAmount() <= 0 {
		err := TransferReqValidationError{
			field:  "Amount",
			reason: "value must be greater than 0",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Currency

	if len(errors) > 0 {
		return TransferReqMultiError(errors)
	}

	return nil
}

// TransferReqMultiError is an error wrapping multiple validation errors
// returned by TransferReq.ValidateAll() if the designated constraints aren't met.
type TransferReqMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferReqMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferReqMultiError) AllErrors() []error { return m }

// TransferReqValidationError is the validation error returned by
// TransferReq.Validate if the designated constraints aren't met.
type TransferReqValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferReqValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferReqValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferReqValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferReqValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferReqValidationError) ErrorName() string { return "TransferReqValidationError" }

// Error satisfies the builtin error interface
func (e TransferReqValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferReq.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferReqValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferReqValidationError{}

// Validate checks the field values on TransferRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TransferRsp) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TransferRsp with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TransferRspMultiError, or
// nil if none found.
func (m *TransferRsp) ValidateAll() error {
	return m.validate(true)
}

func (m *TransferRsp) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetFromAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransferRspValidationError{
					field:  "FromAccount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransferRspValidationError{
					field:  "FromAccount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetFromAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransferRspValidationError{
				field:  "FromAccount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetToAccount()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, TransferRspValidationError{
					field:  "ToAccount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, TransferRspValidationError{
					field:  "ToAccount",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetToAccount()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return TransferRspValidationError{
				field:  "ToAccount",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return TransferRspMultiError(errors)
	}

	return nil
}

// TransferRspMultiError is an error wrapping multiple validation errors
// returned by TransferRsp.ValidateAll() if the designated constraints aren't met.
type TransferRspMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TransferRspMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TransferRspMultiError) AllErrors() []error { return m }

// TransferRspValidationError is the validation error returned by
// TransferRsp.Validate if the designated constraints aren't met.
type TransferRspValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TransferRspValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TransferRspValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TransferRspValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TransferRspValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TransferRspValidationError) ErrorName() string { return "TransferRspValidationError" }

// Error satisfies the builtin error interface
func (e TransferRspValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTransferRsp.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TransferRspValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TransferRspValidationError{}
